---
name: metenp
channels:
  - conda-forge
dependencies:
  - r-base
  - r-base=3.6
  - r-essentials
  - r-devtools
  - r-biocmanager
  - r-plyr
  - r-dplyr
  - r-tidyr
  - r-purrr
  - r-reshape2
  - r-ggplot2
  - r-igraph
  - r-httr
  - r-stringr
  - r-jsonlite
  - r-rjson
  - r-tidyverse
  - r-magrittr
  - r-tidygraph
  - r-ggrepel
  - r-ggraph
  - r-insight
  - r-bh
  - r-png
  - r-bitops
  - r-rcurl
  - r-xml
  - r-bit
  - r-plogr
  - r-bit64
  - r-rsqlite
  - r-sjlabelled
  - r-sjmisc